### ISSUE TITLE
Add Register with google and facebook 

### ISSUE THREAD

**Issue by kungFuLambda** [Yog3sh56/save-the-scran#31]

**Comment by Yog3sh56** [comment]
Google login and facebook login are more like continue with Google or with Facebook rather than register🤔. What we can do is, we have that page with animation that has login and registration button, we can remove registration button and replace with continue with google and continue with facebook. We have link to registration page inside login page anyway. 🤔

**Comment by Yog3sh56** [comment]
Or I can copy exact same thing that is on login page to registration page. Is that what you mean?
